
#########################################################
#        ____            __ _    ____ ____ _____        #
#       / ___|_ __ __ _ / _| |_ / ___|  _ \_   _|       #
#       | |   | '__/ _` | |_| __| |  _| |_) || |        #
#       | |___| | | (_| |  _| |_| |_| |  __/ | |        #
#       \____|_|  \__,_|_|  \__|\____|_|    |_|         #
#                                                       #
#  Join the Discord at: https://discord.gg/BXhUUQEymg   #
#########################################################




# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                  CRITICAL CONFIGURATION                                      | #
# |                                                                                              | #
# |                           - required for CraftGPT to work! -                                 | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

api_key: "API KEY HERE"

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                        Main settings                                         | #
# |                                                                                              | #
# |                                 Customize CraftGPT's core                                    | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# OpenAI API settings:
default-temperature: 1.0
messages-cutoff: 8 # How many messages are sent to the API per chat. Higher means longer "memories" and higher API usage
timeout: 10 # Seconds before the HTTP connection times out and the request is retried
proxy: # Supports HTTP proxies. Do not enable/configure unless your internet access blocks OpenAI.
  enabled: false
  host: "0.0.0.0"
  port: 1000

# In-game interaction settings
interaction-radius: 30 # Setting this too high will cause lag!

# Auto-spawn settings
# With this enabled, all mobs that spawn naturally in the below worlds will have a % chance of becoming AI-enabled
auto-spawn:
  enabled: false
  chance: 1.5 # Percentage where 1.5 = 1.5%
  # NOTE: Backstories and names for auto-spawned AI mobs are randomly generated.
  # Any string in prompt-appendix will be appended to the prompt/personality of EVERY auto-spawned mob
  # Use it for details about your server or world that you want the mobs to know
  prompt-appendix: "" # Leave blank for personalities to be completely random
  worlds:
    - "world"
    - "world_the_end"
    - "world_nether"


# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                        Usage limits                                          | #
# |                                                                                              | #
# |                               Limit API usage using permissions                              | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Example: Use permission 'craftgpt.usage-limit.high' to set player's token limit to the 'high' category
# If a player does not have a specific usage-limit permission, they will inherit the default-usage-limit
# If a player has multiple usage-limit permissions, the limit will be set to the lowest permission the player has

default-usage-limit: 25000
global-usage-limit: 3000000 # Maximum token usage for the entire server

usage-limit:
  high:
    max: 50000
  medium:
    max: 25000
  low:
    max: 10000


# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                            Events                                            | #
# |                                                                                              | #
# |                        Customize how AI-mobs react to in-game events                         | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# ==== Don't touch the settings below unless you know what you're doing ====
player-event-prefix: "your friend %s"
passive-event-prefix: "" # Left blank on purpose!
event-indicator: "[event]"
# ==== Don't touch the settings above unless you know what you're doing ====

events:
  player-fish:
    chance: 20
    message: "just caught a %s with a fishing rod"
  player-kill-friend:
    chance: 20
    message: "just killed you!"
  player-kill-entity:
    chance: 20
    message: "just killed a %s"
  player-breed-entity:
    chance: 20
    message: "bred two %ss and they just made a baby %s"
  player-mount:
    chance: 20
    message: "just mounted a %s to ride it"
  player-pickup-item:
    chance: 20
    message: "just picked up a %s"
  player-resurrect:
    chance: 20
    message: "just resurrected from the dead"
  player-tame-entity:
    chance: 20
    message: "just tamed a %s"
  player-eat:
    chance: 20
    message: "just ate a %s"
  player-hit-friend-projectile:
    chance: 20
    message: "just shot you with a %s"
  player-hit-entity-projectile:
    chance: 20
    message: "just shot a %s with a %s"
  player-damage-friend:
    chance: 20
    message: "just hit you with a %s"
  player-damage-friend-fist:
    chance: 20
    message: "just hit you with their fist"
  player-damage-entity:
    chance: 20
    message: "just hit a %s"
  player-break-item:
    chance: 20
    message: "just broke their %s"
  player-levelup:
    chance: 20
    message: "just went up in experience level"
  player-leash-entity:
    chance: 20
    message: "just attached a leash to a %s"

# Events where player is damaged by something
  player-hurt-suffocation:
    chance: 20
    message: "just got hurt by suffocation"
  player-hurt-lightning:
    chance: 20
    message: "just got hit by lightning and took damage"
  player-hurt-lava:
    chance: 20
    message: "just got burned by lava and took damage"
  player-hurt-fire:
    chance: 20
    message: "just got burned by fire and took damage"
  player-hurt-fall:
    chance: 20
    message: "just got hurt in a fall"
  player-hurt-entityexplosion:
    chance: 20
    message: "just got hurt by an explosion"

# Events where AI-enabled mob damages something else
  npc-damage-entity:
    chance: 20
    message: "you just hit a %s"
  npc-kill-entity:
    chance: 20
    message: "you just killed a %s"

# Events where AI-enabled mob is damaged by something
  npc-hurt-entity:
    chance: 20
    message: "something just hit you and you took damage"
  npc-hurt-entityexplosion:
    chance: 20
    message: "something just exploded near you and you took damage"
  npc-hurt-fall:
    chance: 20
    message: "you just fell and took damage"
  npc-hurt-fire:
    chance: 20
    message: "you just took damage from touching fire"
  npc-hurt-lava:
    chance: 20
    message: "you just took damage from touching lava"
  npc-hurt-projectile:
    chance: 20
    message: "you just took damage from a projectile"
  npc-hurt-fire-tick:
    chance: 20
    message: "you just took damage from being on fire"
  npc-hurt-drowning:
    chance: 20
    message: "you just took damage from drowning"
