name: CraftGPT
version: '${project.version}'
main: acute.ai.CraftGPT
api-version: 1.19
authors: [ zizmax ]
description: AI mobs in Minecraft
softdepend: [PlaceholderAPI]
commands:
  craftgpt:
    description: CraftGPT root command
    usage: <command> [subcommand]
    aliases: [cg]

permissions:
  craftgpt.*:
    description:
